/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * My AR Project API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 花火を作成するためのリクエストボディ
 */
export interface FireworkCreateRequest {
	/** 花火が共有可能かどうか */
	isShareable: boolean;
	/** 花火の元となる画像ファイル */
	image: Blob;
}

/**
 * 花火のレスポンスデータ
 */
export interface FireworkResponse {
	/** 花火のID */
	id: number;
	/** 花火が共有可能かどうか */
	isShareable: boolean;
	/**
	 * 元画像の公開URL。旧レコードは null
	 * （旧フィールド pixelData: boolean[] は廃止）
	 */
	imageUrl: string | null;
	/** 花火の作成日時 */
	createdAt?: string;
	/** 花火の更新日時 */
	updatedAt?: string;
}

/**
 * 花火を更新するためのリクエストボディ
 */
export interface FireworkUpdateRequest {
	/** 花火が共有可能かどうか */
	isShareable: boolean;
}